//
// This file was generated by the Jeddict
//
package com.app.enties;

import java.io.Serializable;

public class AccountPK implements Serializable {

    private int accountId;

    private int merchantServicesserviceId;

    private int merchantServicesMerchantuserId;

    public AccountPK() {
    }

    public AccountPK(int accountId, int merchantServicesserviceId, int merchantServicesMerchantuserId) {
        this.accountId = accountId;
        this.merchantServicesserviceId = merchantServicesserviceId;
        this.merchantServicesMerchantuserId = merchantServicesMerchantuserId;
    }

    public int getAccountId() {
        return this.accountId;
    }

    public void setAccountId(int accountId) {
        this.accountId = accountId;
    }

    public int getMerchantServicesserviceId() {
        return this.merchantServicesserviceId;
    }

    public void setMerchantServicesserviceId(int merchantServicesserviceId) {
        this.merchantServicesserviceId = merchantServicesserviceId;
    }

    public int getMerchantServicesMerchantuserId() {
        return this.merchantServicesMerchantuserId;
    }

    public void setMerchantServicesMerchantuserId(int merchantServicesMerchantuserId) {
        this.merchantServicesMerchantuserId = merchantServicesMerchantuserId;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final AccountPK other = (AccountPK) obj;
        if (!java.util.Objects.equals(this.getAccountId(), other.getAccountId())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getMerchantServicesserviceId(), other.getMerchantServicesserviceId())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getMerchantServicesMerchantuserId(), other.getMerchantServicesMerchantuserId())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 37 * hash + this.getAccountId();
        hash = 37 * hash + this.getMerchantServicesserviceId();
        hash = 37 * hash + this.getMerchantServicesMerchantuserId();
        return hash;
    }

    @Override
    public String toString() {
        return "AccountPK{" + " accountId=" + accountId + ", merchantServicesserviceId=" + merchantServicesserviceId + ", merchantServicesMerchantuserId=" + merchantServicesMerchantuserId + '}';
    }

}
