//
// This file was generated by the Jeddict
//
package com.app.enties;

import java.io.Serializable;

public class AdminPK implements Serializable {

    private int userId;

    private int postionId;

    private int branchId;

    public AdminPK() {
    }

    public AdminPK(int userId, int postionId, int branchId) {
        this.userId = userId;
        this.postionId = postionId;
        this.branchId = branchId;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getPostionId() {
        return this.postionId;
    }

    public void setPostionId(int postionId) {
        this.postionId = postionId;
    }

    public int getBranchId() {
        return this.branchId;
    }

    public void setBranchId(int branchId) {
        this.branchId = branchId;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final AdminPK other = (AdminPK) obj;
        if (!java.util.Objects.equals(this.getUserId(), other.getUserId())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getPostionId(), other.getPostionId())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getBranchId(), other.getBranchId())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 47 * hash + this.getUserId();
        hash = 47 * hash + this.getPostionId();
        hash = 47 * hash + this.getBranchId();
        return hash;
    }

    @Override
    public String toString() {
        return "AdminPK{" + " userId=" + userId + ", postionId=" + postionId + ", branchId=" + branchId + '}';
    }

}
