/**
 * This file was generated by the Jeddict
 */
package com.app.enties;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name = "Admin")
@IdClass(AdminPK.class)
public class Admin {

    @Column(name = "userId", table = "Admin", nullable = false)
    @Id
    private int userId;

    @Column(name = "postionId", table = "Admin", nullable = false)
    @Id
    private int postionId;

    @Column(name = "branchId", table = "Admin", nullable = false)
    @Id
    private int branchId;

    @Column(name = "title", table = "Admin")
    @Basic
    private Integer title;

    @Column(name = "firstName", table = "Admin", length = 45)
    @Basic
    private String firstName;

    @Column(name = "lastName", table = "Admin", length = 45)
    @Basic
    private String lastName;

    @ManyToOne(optional = false, targetEntity = Branch.class)
    @JoinColumn(name = "BRANCHID", referencedColumnName = "BRANCHID", insertable = false, updatable = false)
    private Branch branch;

    @ManyToOne(optional = false, targetEntity = Postion.class)
    @JoinColumn(name = "POSTIONID", referencedColumnName = "POSTIONID", insertable = false, updatable = false)
    private Postion postion;

    @ManyToOne(optional = false, targetEntity = User.class)
    @JoinColumn(name = "USERID", referencedColumnName = "USERID", insertable = false, updatable = false)
    private User user;

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getPostionId() {
        return this.postionId;
    }

    public void setPostionId(int postionId) {
        this.postionId = postionId;
    }

    public int getBranchId() {
        return this.branchId;
    }

    public void setBranchId(int branchId) {
        this.branchId = branchId;
    }

    public Integer getTitle() {
        return this.title;
    }

    public void setTitle(Integer title) {
        this.title = title;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Branch getBranch() {
        return this.branch;
    }

    public void setBranch(Branch branch) {
        this.branch = branch;
    }

    public Postion getPostion() {
        return this.postion;
    }

    public void setPostion(Postion postion) {
        this.postion = postion;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

}
