//
// This file was generated by the Jeddict
//
package com.app.enties;

import java.io.Serializable;

public class ContactInfoPK implements Serializable {

    private int contactId;

    private int userId;

    public ContactInfoPK() {
    }

    public ContactInfoPK(int contactId, int userId) {
        this.contactId = contactId;
        this.userId = userId;
    }

    public int getContactId() {
        return this.contactId;
    }

    public void setContactId(int contactId) {
        this.contactId = contactId;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final ContactInfoPK other = (ContactInfoPK) obj;
        if (!java.util.Objects.equals(this.getContactId(), other.getContactId())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getUserId(), other.getUserId())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 53 * hash + this.getContactId();
        hash = 53 * hash + this.getUserId();
        return hash;
    }

    @Override
    public String toString() {
        return "ContactInfoPK{" + " contactId=" + contactId + ", userId=" + userId + '}';
    }

}
