/**
 * This file was generated by the Jeddict
 */
package com.app.enties;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

@Entity
@Table(name = "Customer")
public class Customer {

    @Column(name = "userId", table = "Customer", nullable = false)
    @Id
    private Integer userId;

    @Column(name = "title", table = "Customer", length = 5)
    @Basic
    private String title;

    @Column(name = "firstName", table = "Customer", length = 45)
    @Basic
    private String firstName;

    @Column(name = "lostName", table = "Customer", length = 45)
    @Basic
    private String lostName;

    @Column(name = "dob", table = "Customer", length = 45)
    @Basic
    private String dob;

    @OneToOne(optional = false, targetEntity = User.class, mappedBy = "customer")
    @JoinColumn(name = "USERID", referencedColumnName = "USERID", insertable = false, updatable = false)
    private User user;

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLostName() {
        return this.lostName;
    }

    public void setLostName(String lostName) {
        this.lostName = lostName;
    }

    public String getDob() {
        return this.dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

}
