/**
 * This file was generated by the Jeddict
 */
package com.app.enties;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "LoginHistory")
@IdClass(LoginHistoryPK.class)
public class LoginHistory {

    @Column(name = "id", table = "LoginHistory", nullable = false)
    @Id
    private int id;

    @Column(name = "userId", table = "LoginHistory", nullable = false)
    @Id
    private int userId;

    @Column(name = "time", table = "LoginHistory")
    @Basic
    @Temporal(TemporalType.DATE)
    private Date time;

    @Column(name = "ipAddress", table = "LoginHistory", length = 132)
    @Basic
    private String ipAddress;

    @ManyToOne(optional = false, targetEntity = User.class)
    @JoinColumn(name = "USERID", referencedColumnName = "USERID", insertable = false, updatable = false)
    private User user;

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public Date getTime() {
        return this.time;
    }

    public void setTime(Date time) {
        this.time = time;
    }

    public String getIpAddress() {
        return this.ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

}
