/**
 * This file was generated by the Jeddict
 */
package com.app.enties;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

@Entity
@Table(name = "LoginInfo")
public class LoginInfo {

    @Column(name = "userId", table = "LoginInfo", nullable = false)
    @Id
    private Integer userId;

    @Column(name = "userName", table = "LoginInfo", nullable = false, length = 45)
    @Basic(optional = false)
    private String userName;

    @Column(name = "password", table = "LoginInfo", nullable = false, length = 45)
    @Basic(optional = false)
    private String password;

    @Column(name = "sequrityAns", table = "LoginInfo", length = 45)
    @Basic
    private String sequrityAns;

    @Column(name = "defaultIP", table = "LoginInfo", length = 132)
    @Basic
    private String defaultIP;

    @OneToOne(optional = false, targetEntity = User.class, mappedBy = "loginInfo")
    @JoinColumn(name = "USERID", referencedColumnName = "USERID", insertable = false, updatable = false)
    private User user;

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getSequrityAns() {
        return this.sequrityAns;
    }

    public void setSequrityAns(String sequrityAns) {
        this.sequrityAns = sequrityAns;
    }

    public String getDefaultIP() {
        return this.defaultIP;
    }

    public void setDefaultIP(String defaultIP) {
        this.defaultIP = defaultIP;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

}
