//
// This file was generated by the Jeddict
//
package com.app.enties;

import java.io.Serializable;

public class LoginHistoryPK implements Serializable {

    private int id;

    private int userId;

    public LoginHistoryPK() {
    }

    public LoginHistoryPK(int id, int userId) {
        this.id = id;
        this.userId = userId;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final LoginHistoryPK other = (LoginHistoryPK) obj;
        if (!java.util.Objects.equals(this.getId(), other.getId())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getUserId(), other.getUserId())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 47 * hash + this.getId();
        hash = 47 * hash + this.getUserId();
        return hash;
    }

    @Override
    public String toString() {
        return "LoginHistoryPK{" + " id=" + id + ", userId=" + userId + '}';
    }

}
