/**
 * This file was generated by the Jeddict
 */
package com.app.enties;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

@Entity
@Table(name = "Merchant")
public class Merchant {

    @Column(name = "userId", table = "Merchant", nullable = false)
    @Id
    private Integer userId;

    @Column(name = "OrgName", table = "Merchant", nullable = false, length = 45)
    @Basic(optional = false)
    private String orgName;

    @Column(name = "registrationNo", table = "Merchant", nullable = false, length = 45)
    @Basic(optional = false)
    private String registrationNo;

    @Column(name = "taxNo", table = "Merchant", nullable = false, length = 45)
    @Basic(optional = false)
    private String taxNo;

    @Column(name = "logoUrl", table = "Merchant")
    @Basic
    private String logoUrl;

    @OneToOne(optional = false, targetEntity = User.class, mappedBy = "merchant")
    @JoinColumn(name = "USERID", referencedColumnName = "USERID", insertable = false, updatable = false)
    private User user;

    @OneToMany(targetEntity = MerchantServices.class, mappedBy = "merchant")
    private List<MerchantServices> merchantServicesCollection;

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getOrgName() {
        return this.orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getRegistrationNo() {
        return this.registrationNo;
    }

    public void setRegistrationNo(String registrationNo) {
        this.registrationNo = registrationNo;
    }

    public String getTaxNo() {
        return this.taxNo;
    }

    public void setTaxNo(String taxNo) {
        this.taxNo = taxNo;
    }

    public String getLogoUrl() {
        return this.logoUrl;
    }

    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public List<MerchantServices> getMerchantServicesCollection() {
        return this.merchantServicesCollection;
    }

    public void setMerchantServicesCollection(List<MerchantServices> merchantServicesCollection) {
        this.merchantServicesCollection = merchantServicesCollection;
    }

}
