//
// This file was generated by the Jeddict
//
package com.app.enties;

import java.io.Serializable;

public class MerchantServicesPK implements Serializable {

    private int serviceId;

    private int merchantuserId;

    public MerchantServicesPK() {
    }

    public MerchantServicesPK(int serviceId, int merchantuserId) {
        this.serviceId = serviceId;
        this.merchantuserId = merchantuserId;
    }

    public int getServiceId() {
        return this.serviceId;
    }

    public void setServiceId(int serviceId) {
        this.serviceId = serviceId;
    }

    public int getMerchantuserId() {
        return this.merchantuserId;
    }

    public void setMerchantuserId(int merchantuserId) {
        this.merchantuserId = merchantuserId;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final MerchantServicesPK other = (MerchantServicesPK) obj;
        if (!java.util.Objects.equals(this.getServiceId(), other.getServiceId())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getMerchantuserId(), other.getMerchantuserId())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 41 * hash + this.getServiceId();
        hash = 41 * hash + this.getMerchantuserId();
        return hash;
    }

    @Override
    public String toString() {
        return "MerchantServicesPK{" + " serviceId=" + serviceId + ", merchantuserId=" + merchantuserId + '}';
    }

}
