/**
 * This file was generated by the Jeddict
 */
package com.app.enties;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name = "Transaction")
public class Transaction {

    @Column(name = "transactionId", table = "Transaction", nullable = false)
    @Id
    private Integer transactionId;

    @Column(name = "transType", table = "Transaction", length = 45)
    @Basic
    private String transType;

    @Column(name = "currency", table = "Transaction", length = 45)
    @Basic
    private String currency;

    @Column(name = "amount", table = "Transaction", precision = 12)
    @Basic
    private Float amount;

    @ManyToOne(optional = false, targetEntity = Account.class)
    private Account accountId;

    @ManyToOne(optional = false, targetEntity = User.class)
    @JoinColumn(name = "USERID", referencedColumnName = "USERID")
    private User userId;

    public Integer getTransactionId() {
        return this.transactionId;
    }

    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }

    public String getTransType() {
        return this.transType;
    }

    public void setTransType(String transType) {
        this.transType = transType;
    }

    public String getCurrency() {
        return this.currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public Float getAmount() {
        return this.amount;
    }

    public void setAmount(Float amount) {
        this.amount = amount;
    }

    public Account getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Account accountId) {
        this.accountId = accountId;
    }

    public User getUserId() {
        return this.userId;
    }

    public void setUserId(User userId) {
        this.userId = userId;
    }

}
