/**
 * This file was generated by the Jeddict
 */
package com.app.enties;

import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "User")
public class User {

    @Column(name = "userId", table = "User", nullable = false)
    @Id
    private Integer userId;

    @Column(name = "userType", table = "User", nullable = false, length = 45)
    @Basic(optional = false)
    private String userType;

    @Column(name = "creationDate", table = "User", nullable = false)
    @Basic(optional = false)
    @Temporal(TemporalType.DATE)
    private Date creationDate;

    @OneToOne(targetEntity = LoginInfo.class)
    private LoginInfo loginInfo;

    @OneToOne(targetEntity = Customer.class)
    private Customer customer;

    @OneToOne(targetEntity = Merchant.class)
    private Merchant merchant;

    @OneToMany(targetEntity = Account.class, mappedBy = "userId")
    private List<Account> accountCollection;

    @OneToMany(targetEntity = Admin.class, mappedBy = "user")
    private List<Admin> adminCollection;

    @OneToMany(targetEntity = Transaction.class, mappedBy = "userId")
    private List<Transaction> transactionCollection;

    @OneToMany(targetEntity = LoginHistory.class, mappedBy = "user")
    private List<LoginHistory> loginHistoryCollection;

    @OneToMany(targetEntity = ContactInfo.class, mappedBy = "user")
    private List<ContactInfo> contactInfoCollection;

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserType() {
        return this.userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public LoginInfo getLoginInfo() {
        return this.loginInfo;
    }

    public void setLoginInfo(LoginInfo loginInfo) {
        this.loginInfo = loginInfo;
    }

    public Customer getCustomer() {
        return this.customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public Merchant getMerchant() {
        return this.merchant;
    }

    public void setMerchant(Merchant merchant) {
        this.merchant = merchant;
    }

    public List<Account> getAccountCollection() {
        return this.accountCollection;
    }

    public void setAccountCollection(List<Account> accountCollection) {
        this.accountCollection = accountCollection;
    }

    public List<Admin> getAdminCollection() {
        return this.adminCollection;
    }

    public void setAdminCollection(List<Admin> adminCollection) {
        this.adminCollection = adminCollection;
    }

    public List<Transaction> getTransactionCollection() {
        return this.transactionCollection;
    }

    public void setTransactionCollection(List<Transaction> transactionCollection) {
        this.transactionCollection = transactionCollection;
    }

    public List<LoginHistory> getLoginHistoryCollection() {
        return this.loginHistoryCollection;
    }

    public void setLoginHistoryCollection(List<LoginHistory> loginHistoryCollection) {
        this.loginHistoryCollection = loginHistoryCollection;
    }

    public List<ContactInfo> getContactInfoCollection() {
        return this.contactInfoCollection;
    }

    public void setContactInfoCollection(List<ContactInfo> contactInfoCollection) {
        this.contactInfoCollection = contactInfoCollection;
    }

}
